# Gemini-Renamer Default Configuration File
# For more details on placeholders, see README.md or documentation.

[default]

  # --- Core Settings ---
  # Scan subdirectories.
  recursive = false
  # Processing mode: 'auto', 'series', 'movie'.
  processing_mode = "auto"
  # Fetch metadata from APIs.
  use_metadata = true
  # Extract technical stream info (resolution, codecs).
  extract_stream_info = false
  # Preserve original file modification time.
  preserve_mtime = false
  # List of exact directory names to ignore.
  ignore_dirs = []
  # List of glob patterns (e.g., '*.tmp', '.*') to ignore.
  ignore_patterns = [".*", "*.partial", "Thumbs.db", "*[sS]ample*"]

  # --- Format Strings ---
  # Filename format for series episodes.
  series_format = "{show_title} ({show_year})/Season {season:02d}/S{season:02d}{ep_identifier} - {episode_title}"
  # Filename format for movies.
  movie_format = "{movie_title} ({movie_year})/{movie_title} ({movie_year})"
  # Filename format for subtitles.
  subtitle_format = "{stem}{lang_dot}{flags_dot}"
  # Filename format for series specials (Season 00).
  series_format_specials = "{show_title} ({show_year})/Season 00/S00{ep_identifier} - {episode_title}"
  # Folder structure for series.
  folder_format_series = "{show_title} ({show_year})/Season {season:02d}"
  # Folder structure for movies.
  folder_format_movie = "{movie_title} ({movie_year})"
  # Folder structure for series specials.
  folder_format_specials = "{show_title} ({show_year})/Season 00"

  # --- File Handling & Extensions ---
  # List of video file extensions.
  video_extensions = [".mkv", ".mp4", ".avi", ".mov", ".wmv", ".flv", ".webm", ".mpg", ".mpeg", ".m4v", ".ts", ".m2ts"]
  # List of associated file extensions (excluding subtitles).
  associated_extensions = [".nfo", ".txt", ".jpg", ".png", ".sfv"]
  # List of subtitle file extensions.
  subtitle_extensions = [".srt", ".sub", ".ass", ".ssa", ".vtt", ".idx"]
  # Action on filename conflict: 'skip', 'overwrite', 'suffix', 'fail'.
  on_conflict = "skip"
  # Create destination folders if they don't exist.
  create_folders = true
  # How to handle unknown files: 'skip', 'guessit_only', 'move_to_unknown'.
  unknown_file_handling = "skip"
  # Directory for 'move_to_unknown' files (relative to target or absolute).
  unknown_files_dir = "_unknown_files_"
  # Scanning strategy: 'memory', 'low_memory'.
  scan_strategy = "memory"

  # --- Scene Tags ---
  # Include scene tags in the final filename.
  scene_tags_in_filename = true
  # List of scene tags to preserve if found.
  scene_tags_to_preserve = ["PROPER", "REPACK", "READ.NFO", "INTERNAL", "LIMITED", "UNCUT", "UNRATED", "DIRECTORS.CUT", "EXTENDED", "REMASTERED", "COMPLETE"]

  # --- Subtitles ---
  # Attempt to detect subtitle encoding (requires 'chardet').
  subtitle_encoding_detection = true

  # --- API & Metadata Options ---
  # Delay (seconds) between API calls.
  api_rate_limit_delay = 0.5
  # Number of retry attempts for API calls.
  api_retry_attempts = 3
  # Wait time (seconds) between API retry attempts.
  api_retry_wait_seconds = 2.0
  # Year tolerance for matching API results.
  api_year_tolerance = 1
  # TMDB matching strategy: 'first', 'fuzzy'.
  tmdb_match_strategy = "first"
  # Minimum score for 'fuzzy' TMDB match.
  tmdb_match_fuzzy_cutoff = 70
  # Minimum fuzzy score for a 'first' strategy TMDB match to be considered valid (requires 'thefuzz').
  tmdb_first_result_min_score = 65
  # Interactively confirm metadata match if score is below this value (0-100).
  # confirm_match_below = # (not set, uses internal default or None)
  # Preferred metadata source order for series.
  series_metadata_preference = ["tmdb", "tvdb"]

  # --- Caching Options ---
  # Enable API response caching.
  cache_enabled = true
  # Custom cache directory (default: user cache dir).
  # cache_directory = # (not set, uses internal default or None)
  # Cache expiration time in seconds (default: 7 days).
  cache_expire_seconds = 604800

  # --- Undo Options ---
  # Enable undo logging.
  enable_undo = true
  # Path to undo database file (default: in app dir).
  # undo_db_path = # (not set, uses internal default or None)
  # Days to keep undo logs (-1 for forever, 0 for session only).
  undo_expire_days = 30
  # Verify file integrity before undoing (size, mtime).
  undo_check_integrity = false
  # Bytes to hash for integrity check (0 to disable partial hash).
  undo_integrity_hash_bytes = 0
  # Calculate full file hash for undo integrity check (SLOW, overrides hash_bytes).
  undo_integrity_hash_full = false

  # --- Logging Options ---
  # Path to log file (e.g., rename_app.log).
  # log_file = # (not set, uses internal default or None)
  # Logging level: DEBUG, INFO, WARNING, ERROR.
  log_level = "INFO"

# You can create other profiles, e.g.:
# [movie_profile]
# movie_format = "{movie_title} [{movie_year}] - {resolution}"
# use_metadata = true