[default]
# General settings applied unless overridden by a profile or command line
log_file = "renamer.log"
log_level = "INFO"
enable_undo = true
use_metadata = true
recursive = true
processing_mode = "auto"
on_conflict = "skip" # skip, overwrite, suffix, fail
api_rate_limit_delay = 0.5 # seconds between API calls
# Enable extraction (can also use --use-stream-info flag)
extract_stream_info = true
preserve_mtime = true
# --- Formats ---
series_format = "S{season:0>2}E{episode:0>2}{ext}"
movie_format = "{movie_title} ({movie_year}){ext}"
subtitle_format = "{stem}.{lang_code}{flags_dot}{ext}" # Placeholders: stem, lang_code, flags_dot (like .forced), ext
# --- Folder Structure (Optional) ---
create_folders = true
folder_format_series = "{show_title} ({show_year})/Season {season:0>2}"
folder_format_movie = "{movie_title} ({movie_year})"
# --- Extensions ---
video_extensions = [".mkv", ".mp4", ".avi", ".mov", ".wmv"]
associated_extensions = [".srt", ".sub", ".ssa", ".ass", ".vtt", ".nfo", ".jpg", ".png"]
# --- Unknown File Handing ---
unknown_file_handling = "move_to_unknown"  # or "guessit_only" or "skip"
unknown_files_dir = "_unknown_files_"

# List of exact directory names to completely ignore during scanning.
# Useful for system folders, temporary download folders, etc. Case-sensitive.
# ignore_dirs = [".git", ".vscode", "@eaDir", "lost+found", "_temp_downloads"]
ignore_dirs = []

# List of glob patterns to ignore files OR directories during scanning.
# Uses standard glob syntax (like shell patterns). Case-sensitivity depends on OS.
# Examples:
#   ".*"         - Ignore all dotfiles and dot-directories
#   "*.tmp"      - Ignore files ending in .tmp
#   "~*"         - Ignore files starting with ~ (often temporary files)
#   "*.partial"  - Ignore partial download files
#   "Thumbs.db"  - Ignore Windows thumbnail cache
#   "* - sample" - Ignore sample files (adjust pattern as needed)
ignore_patterns = [".*", "*.partial", "Thumbs.db", "*[sS]ample*"]

# series_format = "{show_title} ({show_year})/Season {season:02d}/S{season:02d}E{episode:02d} - {episode_title}"
# folder_format_series = "{show_title} ({show_year})" # Note: Season folder added by series_format

# Optional: Add specific formats for Season 00 / Specials
# series_format_specials = "{show_title} ({show_year})/Specials/S00E{episode:02d} - {episode_title}"
# folder_format_specials = "{show_title} ({show_year})" # Keep specials in the main show folder

# Or maybe put specials directly in the show folder:
# series_format_specials = "{show_title} ({show_year})/S00E{episode:02d} - {episode_title}"
# folder_format_specials = "{show_title} ({show_year})" # No specific "Specials" subfolder

# Or maybe a dedicated Specials folder at the top level?
# series_format_specials = "Specials/{show_title} - S00E{episode:02d} - {episode_title}"
# folder_format_specials = "Specials" # Simple top-level Specials folder

# ... other settings ...





[profile.plex_optimized]
# Example profile overriding some defaults
series_format = "{show_title} - S{season:0>2}E{episode:0>2} - {episode_title} [{quality} {audio_codec}]{ext}" # Assuming guessit provides these
movie_format = "{movie_title} ({movie_year}) [{quality}]{ext}"

# Example formats using stream information based placeholders
#movie_format = "{movie_title} ({movie_year}) [{resolution} {vcodec} {acodec} {achannels}]{ext}"
#series_format = "{show_title} - S{season:0>2}E{episode:0>2} - {episode_title} [{resolution} {vcodec}]{ext}"

# Example using collection in folder format
folder_format_movie = "Movies/{collection}/{movie_title} ({movie_year})"
folder_format_series = "TV Shows/{show_title}/Season {season:0>2}"

# Other settings...
create_folders = true
on_conflict = "suffix"
unknown_file_handling = "move_to_unknown"  # or "guessit_only" or "skip"
unknown_files_dir = "_unknown_files_"

[profile.simple_tv]
processing_mode = "series"
series_format = "S{season:0>2}E{episode:0>2}{ext}"
use_metadata = false
create_folders = false

[profile.downloads]
# Profile for a downloads folder where you want to move unknowns
unknown_file_handling = "move_to_unknown"
unknown_files_dir = "_needs_sorting_" # Custom unknown dir for this profile
recursive = true # Override recursive setting for this profile
preserve_mtime = true

[profile.archive]
# Profile for an archive where you might want to try renaming based on filename only
unknown_file_handling = "guessit_only"
# It will use the default series_format unless overridden here
# It will use the default preserve_mtime (false) unless overridden here


# Add more profiles as needed
